/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface UiWaterJar {
        "color": string;
        "shape": string;
        "value": number;
    }
}
declare global {
    interface HTMLUiWaterJarElement extends Components.UiWaterJar, HTMLStencilElement {
    }
    var HTMLUiWaterJarElement: {
        prototype: HTMLUiWaterJarElement;
        new (): HTMLUiWaterJarElement;
    };
    interface HTMLElementTagNameMap {
        "ui-water-jar": HTMLUiWaterJarElement;
    }
}
declare namespace LocalJSX {
    interface UiWaterJar {
        "color"?: string;
        "shape"?: string;
        "value"?: number;
    }
    interface IntrinsicElements {
        "ui-water-jar": UiWaterJar;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ui-water-jar": LocalJSX.UiWaterJar & JSXBase.HTMLAttributes<HTMLUiWaterJarElement>;
        }
    }
}
